// Permission constants for authorization checks
export const PERMISSIONS = {
  // Assess permissions
  ASSESS_ACCESS: 'ASSESS_ACCESS',
  ASSESS_CREATE: 'ASSESS_CREATE',
  ASSESS_UPDATE: 'ASSESS_UPDATE',
  ASSESS_DELETE: 'ASSESS_DELETE',

  // Analyze permissions
  ANALYZE_ACCESS: 'ANALYZE_ACCESS',
  ANALYZE_CREATE: 'ANALYZE_CREATE',
  ANALYZE_UPDATE: 'ANALYZE_UPDATE',
  ANALYZE_DELETE: 'ANALYZE_DELETE',

  // Publish permissions
  PUBLISH_ACCESS: 'PUBLISH_ACCESS',
  PUBLISH_CREATE: 'PUBLISH_CREATE',
  PUBLISH_UPDATE: 'PUBLISH_UPDATE',
  PUBLISH_DELETE: 'PUBLISH_DELETE',

  // My Assets permissions
  MY_ASSETS_ACCESS: 'MY_ASSETS_ACCESS',
  MY_ASSETS_CREATE: 'MY_ASSETS_CREATE',
  MY_ASSETS_UPDATE: 'MY_ASSETS_UPDATE',
  MY_ASSETS_DELETE: 'MY_ASSETS_DELETE',

  // Config permissions
  CONFIG_ACCESS: 'CONFIG_ACCESS',
  CONFIG_OSINT_SOURCE_ACCESS: 'CONFIG_OSINT_SOURCE_ACCESS',
  CONFIG_OSINT_SOURCE_GROUP_ACCESS: 'CONFIG_OSINT_SOURCE_GROUP_ACCESS',
  CONFIG_BOTS_ACCESS: 'CONFIG_BOTS_ACCESS',
  CONFIG_PRODUCT_TYPE_ACCESS: 'CONFIG_PRODUCT_TYPE_ACCESS',
  CONFIG_ATTRIBUTE_ACCESS: 'CONFIG_ATTRIBUTE_ACCESS',
  CONFIG_REPORT_TYPE_ACCESS: 'CONFIG_REPORT_TYPE_ACCESS',
  CONFIG_WORD_LIST_ACCESS: 'CONFIG_WORD_LIST_ACCESS',
  CONFIG_ORGANIZATION_ACCESS: 'CONFIG_ORGANIZATION_ACCESS',
  CONFIG_USER_ACCESS: 'CONFIG_USER_ACCESS',
  CONFIG_ROLE_ACCESS: 'CONFIG_ROLE_ACCESS',
  CONFIG_ACL_ACCESS: 'CONFIG_ACL_ACCESS',
  CONFIG_PRESENTER_ACCESS: 'CONFIG_PRESENTER_ACCESS',
  CONFIG_PUBLISHER_ACCESS: 'CONFIG_PUBLISHER_ACCESS',
  CONFIG_EXTERNAL_AUTH_ACCESS: 'CONFIG_EXTERNAL_AUTH_ACCESS',
  CONFIG_COLLECTORS_NODE_ACCESS: 'CONFIG_COLLECTORS_NODE_ACCESS',
  CONFIG_PRESENTERS_NODE_ACCESS: 'CONFIG_PRESENTERS_NODE_ACCESS',
  CONFIG_PUBLISHERS_NODE_ACCESS: 'CONFIG_PUBLISHERS_NODE_ACCESS',
  CONFIG_BOTS_NODE_ACCESS: 'CONFIG_BOTS_NODE_ACCESS',

  // Admin permissions
  ADMIN_ACCESS: 'ADMIN_ACCESS'
}

export default PERMISSIONS
