services:
    core:
        environment:
            TARANIS_NG_AUTHENTICATOR: "keycloak"

            OPENID_LOGOUT_URL: "${TARANIS_NG_KEYCLOAK_URL}/realms/taranis-ng/protocol/openid-connect/logout?redirect_uri=GOTO_URL"
            # CLIENT (external Keycloak)
            TARANIS_NG_KEYCLOAK_URL: "https://keycloak.example.com"
            TARANIS_NG_KEYCLOAK_INTERNAL_URL: "https://keycloak.int.example.com"
            TARANIS_NG_KEYCLOAK_CLIENT_ID: "taranis-ng"
            KEYCLOAK_VERSION: "25.0.6"
            KEYCLOAK_REALM_NAME: "taranis-ng"
            KEYCLOAK_USER_MANAGEMENT: "false"
            # needed if KEYCLOAK_USER_MANAGEMENT = true
            KEYCLOAK_ADMIN_USERNAME: "admin"
            KEYCLOAK_VERIFY: "true"
        secrets:
            - keycloak_client_secret_key
            #- keycloak_admin_password

    gui:
        environment:
            VUE_APP_TARANIS_NG_LOGIN_URL: "${TARANIS_NG_KEYCLOAK_URL}/realms/taranis-ng/protocol/openid-connect/auth?response_type=code&client_id=taranis-ng&redirect_uri=TARANIS_GUI_URI"
            VUE_APP_TARANIS_NG_LOGOUT_URL: "${TARANIS_NG_KEYCLOAK_URL}/realms/taranis-ng/protocol/openid-connect/logout"

secrets:
    keycloak_client_secret_key:
        file: ./secrets/keycloak_client_secret_key.txt
    keycloak_admin_password:
        file: ./secrets/keycloak_admin_password.txt
