name: CI/CD

on:
  push:
    branches:
    - master
    - awake
    tags:
    - '**'
  pull_request:
jobs:
  build:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get ghcr owner repository
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push core
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.core
          push: true
          tags: ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-core:latest

