name: Docker image - GUI

on:
  push:
    paths:
    - 'src/gui/**'
    - 'docker/Dockerfile.gui'
    - 'VERSION.md'
    branches:
    - main

permissions:
  packages: write

jobs:
  build:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get ghcr owner repository
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push gui
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile.gui
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-gui:${{ github.ref_name }}
