name: CI_Core

on:
  push:
    paths:
    - 'src/core/**'
    - 'docker/**'
    branches:
    - master
    - awake
    tags:
    - '**'

permissions:
  packages: write
  contents: write

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        working-directory: src/core
        run: |
          python -m pip install --upgrade -r ../../dev_requirements.txt
          pip install -e .
          pytest

  build_wheel:
    name: build wheel
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: src/core
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/core/dist/taranis_ng_core-*.whl
            src/core/dist/taranis_ng_core-*.tar.gz

  build_docker:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get ghcr owner repository
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push core
        uses: docker/build-push-action@v3
        with:
          file: docker/Dockerfile.core
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-core:latest
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-core:${{ github.ref_name }}
