name: Docker image - Collectors

on:
  push:
    paths:
    - 'src/collectors/**'
    - 'docker/Dockerfile.collectors'
    - 'docker/start.sh'
    - 'docker/prestart.sh'
    - 'docker/entrypoint.sh'
    - 'docker/gunicorn_conf.py'
    branches:
    - main

permissions:
  packages: write

jobs:
  build:
    name: build docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get ghcr owner repository
        run: |
          echo "GHCR_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Build and push collectors
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile.collectors
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_OWNER }}/taranis-ng-collectors:${{ github.ref_name }}
