name: Update git_version.txt

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_git_version:
    name: Update git_version.txt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update git_version.txt
        run: |
          echo "${GITHUB_SHA::7}" > git_version.txt
          echo "$(date -u +%Y-%m-%d)" >> git_version.txt

      - name: Commit git_version.txt
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add git_version.txt
          git commit -m "Update git_version.txt" || echo "No changes"
          git push
